import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { buildBook } from '../tools/build-book.mjs'

test('builds local HTML and a search index from Markdown chapters', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'course-tutor-book-'))
  try {
    fs.mkdirSync(path.join(root, 'notes', 'chapters'), { recursive: true })
    fs.mkdirSync(path.join(root, 'tools', 'site'), { recursive: true })
    fs.mkdirSync(path.join(root, 'node_modules'), { recursive: true })
    fs.mkdirSync(path.join(root, 'study-data'), { recursive: true })
    fs.mkdirSync(path.join(root, '.study-cache', 'sources', 'lecture-a'), { recursive: true })
    fs.symlinkSync(path.join(process.cwd(), 'node_modules', 'katex'), path.join(root, 'node_modules', 'katex'), process.platform === 'win32' ? 'junction' : 'dir')
    fs.writeFileSync(path.join(root, 'course.yml'), 'course:\n  code: TEST-101\n  title: Test Course\n  current_week: 1\n')
    fs.writeFileSync(path.join(root, 'sources.yml'), 'sources:\n  - id: lecture-a\n    type: lecture\n    title: Lecture A\n    path: materials/lecture-a.pdf\n    week: 1\n')
    fs.writeFileSync(path.join(root, 'study-data', 'progress.yml'), 'version: 1\ncheckpoint:\n  week: 1\n  source_id: lecture-a\n  slide_id: lecture-a-slide-001\nslides:\n  lecture-a-slide-001:\n    status: understood\nconcepts:\n  cpu-datapath:\n    related_slides:\n      - lecture-a-slide-001\n    confidence: 1\n    review_priority: high\n')
    fs.writeFileSync(path.join(root, '.study-cache', 'sources', 'lecture-a', 'manifest.json'), '{"source_id":"lecture-a","page_count":1}\n')
    fs.writeFileSync(path.join(root, 'notes', 'index.md'), '# Test Course\n')
    fs.writeFileSync(path.join(root, 'notes', 'guide.md'), '# Guide\n')
    fs.writeFileSync(path.join(root, 'notes', 'chapters', 'week-01.md'), '# Week 1\n\n## lecture-a\n\n<!-- search:start lecture-a-slide-001 -->\n<span id="lecture-a-slide-001" class="slide-anchor" aria-hidden="true"></span>\n\n### Slide 1\n\nCPU datapath $x + y$.\n\n$$\n\\begin{bmatrix}\nx\\\\\ny\n\\end{bmatrix}\n$$\n<!-- search:end -->\n')
    fs.copyFileSync(path.join(process.cwd(), 'tools', 'site', 'style.css'), path.join(root, 'tools', 'site', 'style.css'))
    fs.copyFileSync(path.join(process.cwd(), 'tools', 'site', 'book.js'), path.join(root, 'tools', 'site', 'book.js'))

    fs.mkdirSync(path.join(root, 'notes/sections/midterm-prep'), { recursive: true })
    const sectionPath = path.join(root, 'notes/sections/midterm-prep/index.md')
    const authored = '# Midterm prep\n\n[Practice](practice.md)\n\nRevision reasoning $x^2$.\n<!-- personal:start -->\nMy own insight.\n<!-- personal:end -->\n'
    fs.writeFileSync(sectionPath, authored)
    fs.writeFileSync(path.join(root, 'notes/sections/midterm-prep/practice.md'), '# Practice\n\n[Overview](index.md)\n')
    const result = buildBook(root)
    assert.equal(result.pages, 5)
    const sectionHtml = fs.readFileSync(path.join(result.destination, 'sections/midterm-prep/index.html'), 'utf8')
    assert.match(sectionHtml, /Study sections/)
    assert.match(sectionHtml, /href="sections\/midterm-prep\/practice\/"/)
    assert.match(sectionHtml, /class="katex"/)
    assert.equal(fs.readFileSync(sectionPath, 'utf8'), authored)
    const chapterHtmlPath = path.join(result.destination, 'chapters', 'week-01', 'index.html')
    assert.ok(fs.existsSync(chapterHtmlPath))
    const chapterHtml = fs.readFileSync(chapterHtmlPath, 'utf8')
    assert.match(chapterHtml, /<base href="\.\.\/\.\.\/">/)
    assert.match(chapterHtml, /href="assets\/style\.css"/)
    assert.match(chapterHtml, /id="theme-toggle"/)
    assert.match(chapterHtml, /course-book-theme/)
    assert.match(chapterHtml, /class="search-results"/)
    assert.match(chapterHtml, /class="katex"/)
    assert.match(chapterHtml, /class="katex-display"/)
    assert.match(chapterHtml, /<section class="book-slide" data-slide-id="lecture-a-slide-001">/)
    assert.match(chapterHtml, /<section class="book-slide"[\s\S]*CPU datapath[\s\S]*<\/section>/)
    assert.doesNotMatch(chapterHtml, /<p>\$\$/)
    assert.doesNotMatch(chapterHtml, /auto-render/)
    const generatedStyles = fs.readFileSync(path.join(result.destination, 'assets', 'style.css'), 'utf8')
    assert.match(generatedStyles, /\.katex-display[^}]*overflow-x:\s*auto/)
    const homeHtml = fs.readFileSync(path.join(result.destination, 'index.html'), 'utf8')
    assert.match(homeHtml, /class="dashboard"/)
    assert.match(homeHtml, /Resume at Slide 1/)
    assert.match(homeHtml, /1 of 1 slides understood/)
    assert.match(homeHtml, /CPU Datapath/)
    assert.match(homeHtml, /1\/1 prepared/)
    assert.match(homeHtml, /Print \/ Save PDF/)
    const printHtml = fs.readFileSync(path.join(result.destination, 'print', 'index.html'), 'utf8')
    assert.match(printHtml, /Print \/ Save as PDF/)
    assert.match(printHtml, /<base href="\.\.\/">/)
    assert.match(printHtml, /<h1>Guide<\/h1>/)
    assert.match(printHtml, /<h1>Week 1<\/h1>/)
    assert.match(printHtml, /CPU datapath/)
    assert.match(printHtml, /Revision reasoning/)
    const searchIndex = JSON.parse(fs.readFileSync(path.join(result.destination, 'search.json'), 'utf8'))
    assert.ok(searchIndex.some((entry) => entry.title === 'Slide 1' && entry.context === 'Week 1 · lecture-a'))
    assert.ok(searchIndex.some((entry) => entry.path === 'chapters/week-01/#lecture-a-slide-001'))
    assert.ok(searchIndex.some((entry) => entry.text.includes('CPU datapath')))
    assert.ok(searchIndex.some(entry => entry.context === 'Study section' && entry.text.includes('Revision reasoning')))
    const weeklyBefore = fs.readFileSync(path.join(root, 'study-data/progress.yml'), 'utf8')
    fs.writeFileSync(path.join(root, 'study-data/sections.yml'), 'version: 1\nactive_section: midterm-prep\nsections:\n  midterm-prep:\n    title: Midterm prep\n    page: notes/sections/midterm-prep/index.md\n')
    buildBook(root)
    assert.match(fs.readFileSync(path.join(result.destination, 'index.html'), 'utf8'), /Resume Midterm prep/)
    assert.equal(fs.readFileSync(path.join(root, 'study-data/progress.yml'), 'utf8'), weeklyBefore)
  } finally {
    fs.rmSync(root, { recursive: true, force: true })
  }
})
